### ISSUE TITLE
Animated: `useNativeDriver` was not specified

### ISSUE THREAD

**Issue by ertomz** [Naeemur/react-native-wheel-color-picker#1]
Hello! I'm getting a warning when adding this to my react native project:

`Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false``

Here is the code I use. I added useNativeDriver at the end to try to fix the issue, but true/false still gives the same error. 
```
<ColorPicker
      color={'#ffffff'}
      // onColorChange={(color) => setColor(color)}
      // onColorChangeComplete={(color) => setColor(color)}
      thumbSize={40}
      sliderSize={20}
      noSnap={true}
      row={false}
      swatchesLast={false}
      swatches={false}
      discrete={false}
      useNativeDriver={true}
/>
```

Would appreciate any help with this! Thank you!

**Comment by npetar** [comment]
When using Animated.spring or any other Animation specify useNativeDriver: true of useNativeDriver: false.

Example:

Animated.spring(this.position, {
    toValue: { x: 0, y: 0 },
    useNativeDriver: true,
}).start();

**Comment by sungsong88** [comment]
PR made: #2

**Comment by skoky** [comment]
Thank you for fixing this

**Comment by tiagocpeixoto** [comment]
@sungsong88 
Considering that the maintainer has not published a new version in the last 8 months, would you mind publishing a version with your fix using a different package name?

**Comment by Naeemur** [comment]
Hello everyone... Sorry to inform you all that I was very busy with my ongoing projects & could no update this module. I'm hoping to make some updates to the code and documentation by next weekend. Thanks for your support.

**Comment by tiagocpeixoto** [comment]
@Naeemur 
Thanks a lot!

**Comment by Naeemur** [comment]
Merged PR and and made some changes. You may want to use the new props: `shadeWheelThumb`, `shadeSliderThumb`, `autoResetSlider`
