### ISSUE TITLE
onColorChangeComplete prop error: Type '(color: any) => void' is not assignable to type '() => void'

### ISSUE THREAD

**Issue by thespacemanatee** [Naeemur/react-native-wheel-color-picker#12]
I believe this prop should receive a function with color as the argument as that's the whole point of this prop. I console logged 'color' and indeed got a color as a string.

**Comment by LinusU** [comment]
Fixed in #8, not released yet though

**Comment by Naeemur** [comment]
Version 1.2.0 released with PR merged and issues fixed.
