### ISSUE TITLE
Return wrong hex color code 

### ISSUE THREAD

**Issue by ForamPattha** [Naeemur/react-native-wheel-color-picker#25]
onColorChangeComplete and onColorChange method return wrong color code  when color selected and set in TextInput .  Even if select same color it's value change .

**Comment by khzouroussama** [comment]
@ForamPattha I am having the same issue have you found any workaround for this, I believe this is happening as a result of converting HSV to HEX color value

**Comment by ForamPattha** [comment]
> @ForamPattha I am having the same issue have you found any workaround for this, I believe this is happening as a result of converting HSV to HEX color value

Not getting any solution till now . if you found anything then please share here .

**Comment by fukemy** [comment]
did u found any lib better?

**Comment by khzouroussama** [comment]
i patched the library at the time, i don't remember what i did exactly.
but basically converting between HSV and HEX is not deterministic, so i stopped onColorChange from firing when the user changes the color programmatically.

**Comment by Naeemur** [comment]
Should be fixed in v 1.3.0. See README.md please.

**Comment by crjc** [comment]
Appears to still be an issue

e.g. hex code `#85A99B` is turned into `#84A89A` by this lib
