### ISSUE TITLE
Not working properly in scrollview

### ISSUE THREAD

**Issue by ashvanikumar623** [Naeemur/react-native-wheel-color-picker#26]
When i use this color picker inside scrollview the color picker is not working smoothly

**Comment by GenGraphic** [comment]
Same Problem here

**Comment by Naeemur** [comment]
Since no other instance of this issue reported, I am closing this. If issue persists, try using prop useNativeLayout added in v1.3.0 (See README.md please.) If issue still persists, please reopen this issue with steps to reproduce.
