### ISSUE TITLE
revert() api throwing "Uncaught Error: null is not an object (evaluating 'rgb.r')"

### ISSUE THREAD

**Issue by prabhg** [Naeemur/react-native-wheel-color-picker#27]
Calling "revert()" API sometimes throws `Uncaught Error: null is not an object (evaluating 'rgb.r')` from `hex2Hsv` method.

Version of react-native-wheel-color-picker
^1.2.0

Version of react-native
0.66.3

Platforms you faced the error (IOS or Android or both?)
iOS

Expected behavior
revert() should not throw

Actual behavior
It is random occurance. Sometimes it throws above error, other times it works as expected.

Tested environment (Emulator? Real Device?)
Emulator

Steps to reproduce the behavior
```
const colorPickerRef = useRef();
 const [color, setColor] = React.useState(props.color || "#FFF");

return (<View style={styles.wrapper}>
<ColorPicker
          ref={(ref) => (colorPickerRef.current = ref)}
          color={props.color || "#000000"}
          swatchesOnly={false}
          onColorChangeComplete={setColor}
          thumbSize={40}
          sliderHidden
          sliderSize={10}
          noSnap={true}
          row={false}
          swatchesLast={true}
          swatches={false}
          discrete={false}
        />

<Button text="Cancel" onPress={() => colorPickerRef.current?.revert()} />
</View>)
```
<img width="386" alt="color-picker-error" src="https://user-images.githubusercontent.com/3766895/157191532-60a00cb4-4fb8-4d6b-9c50-9c8226229ffb.png">

**Comment by Naeemur** [comment]
Apparently a regex problem. Should be fixed in v 1.3.0.
