### ISSUE TITLE
Can I disable the input?

### ISSUE THREAD

**Issue by evansendra** [Naeemur/react-native-wheel-color-picker#29]
I'd like to be able to call

    <ColorPicker ... disabled={true} />

which would then show the color picker with its current input but without the ability to select a new color.

Is it possible with the current API?

**Comment by KrisLau** [comment]
there's no disabled props from what i can tell but you could probably hack it without giving `setState` in the `onColorChange` / `onColorChangeComplete` or just do `onColorChangeComplete = {color => setColor('the color you want')}`. You could probably submit a pull request to add the feature

**Comment by evansendra** [comment]
Yeah I haven't found it either; right now I have it hacked by essentially resetting the color when the user tries to change

**Comment by Naeemur** [comment]
In v1.3.0
prop added: disabled
See README.md please.
