### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by SaeedBoroo** [Naeemur/react-native-wheel-color-picker#30]
https://user-images.githubusercontent.com/44952036/163141774-2707c8da-df54-48f0-9d8e-e6744d001f86.mp4

please fix this problem (in the video) in the RTL application.
thanks.

**Comment by SaeedBoroo** [comment]
you can use this package.  👍 💯 
`@navid73/react-native-wheel-color-picker-rtl`

**Comment by Naeemur** [comment]
In v1.3.0
prop added: flipTouchX
prop added: flipTouchY
See README.md please.

**Comment by waleedAlmubarak** [comment]
Adding `flipTouchX` worked.
But I got a wired position after.

Note:
Im using version 1.3.1 
my app is RTL

![Screenshot 2024-01-16 at 2 25 16 PM](https://github.com/Naeemur/react-native-wheel-color-picker/assets/22994350/2b83ae95-f172-4518-8f55-44ab4acf75d7)
