### ISSUE TITLE
picker view outside of the circle

### ISSUE THREAD

**Issue by hiren-appaspect** [Naeemur/react-native-wheel-color-picker#36]
![screenshot-iPhone 14 Pro Max-16 0](https://github.com/Naeemur/react-native-wheel-color-picker/assets/82509588/d6bcc0f0-9ffb-4845-9b84-e062b469be2c)

           <ColorPicker
              style={styles.colorPickerStyle}
                color={ThemeObj.bgColor}
                onColorChangeComplete={color => {
                  //console.log('onColorChangeComplete===>', color);
                  selectedPickerColor = color;
                }}
                thumbSize={30}
                sliderSize={30}
                noSnap={false}
                swatches={false}
                row={false}
                gapSize={1000}
              />

how we can solve this issue?

**Comment by Karsten-Larson** [comment]
I have the same issue. It's a shame because the frequency of this error makes it unusable in my project. I found assigning the thumb-size and slider size a state variable that changing the state to a slightly different size upon interaction can help but it still occurs.

**Comment by Karsten-Larson** [comment]
I noticed that for anything that causes the color picker to reload (state of a prop changes or expo fast load update) the component started to work again. Here's a small workaround that I could recommend when I was working on my project. 

```
const [size, setSize] = useState(30);

const generateNewSize = () => {
    // range of possible sizes (can possibly be smaller)
    const min = 29;
    const max = 31;

    // ensures new size is different in order to trigger a reload because the state is now different in the size prop
    let newSize = size;
    while (newSize === size) {
      newSize = Math.random() * (max - min) + min;
    }

    setSize(newSize);
}

return (
    <ColorPicker
        style={styles.colorPickerStyle}
        color={ThemeObj.bgColor}
        onColorChangeComplete={color => {
            selectedPickerColor = color;
         }}
        thumbSize={size}
        sliderSize={size}
        noSnap={false}
        swatches={false}
        row={false}
        gapSize={1000}
        onInteractionStart={generateNewSize}
    />
);
```

Hopefully, this workaround proves helpful to you and this is eventually patched.

**Comment by ArtsiomAstrouski** [comment]
This problem is still relevant

**Comment by javiermojito** [comment]
Hey @dharay that fix works, thanks! good job!

**Comment by Naeemur** [comment]
Added prop useNativeLayout in v1.3.0 with some additional checking. That should fix the issue.
See README.md please.
