### ISSUE TITLE
When user changes color onColorChange fires multiple times

### ISSUE THREAD

**Issue by alperakgun** [Naeemur/react-native-wheel-color-picker#37]
When user changes color on the picker  onColorChange fires multiple times, probably the "state" being applied again.

I think when the state sets `color={currentColor}`, there shouldn't be an event fired.

```
    const someEvent = () => {
          setCurrentColor('#cccccc');
    }
    
    const [currentColor, setCurrentColor} = useState('#ffffff');
    
   <ColorPicker
          color={currentColor}
          onColorChange={setCurrentColor}
    />
```

Possibly related https://github.com/Naeemur/react-native-wheel-color-picker/issues/5

**Comment by Naeemur** [comment]
I think the state setter used as the onChangeColor callback is the problem here. I think with some additional checking these repeating calls can be avoided. Closing this for now.
