### ISSUE TITLE
Dragging in web on mobile

### ISSUE THREAD

**Issue by tickietackie** [Naeemur/react-native-wheel-color-picker#4]
I am trying to use the library with expo web which is working great so far. 

But there is one issue when used in mobile, which is that the dragging of the window is interfering with the dragging of the color-dragger.

This is not working on iOS nor Android. Is there any way to fix this easily?

Issue reproduced on mobile:
[https://snack.expo.io/@hit-em/excited-salsa](https://snack.expo.io/@hit-em/excited-salsa)

https://user-images.githubusercontent.com/25544561/111881135-716a3500-89af-11eb-88b8-c36aa8a43388.mp4

**Comment by Naeemur** [comment]
Dragging on web should be fixed in v1.1.0

**Comment by tickietackie** [comment]
Thanks. I wanted to add, that I had to set the body to

```
body {
  position: fixed;
  overflow: hidden;
}
```

to get this working on iOS, otherwise the body is still scrolling beneath the color-wheel which makes dragging very cumbersome.
