### ISSUE TITLE
Changing color state manually

### ISSUE THREAD

**Issue by eldardzhorobekov** [Naeemur/react-native-wheel-color-picker#5]
My setup is basically something like this:

`

        const someEvent = () => {
              setCurrentColor('#cccccc');
        }
        
        const [currentColor, setCurrentColor} = useState('#ffffff');
        
       <ColorPicker
              color={currentColor}
              onColorChange={setCurrentColor}
        />
`

When `someEvent` function is triggered, `currentColor` is not affecting `<ColorPicker/>` component.

Would appreciate any help with this

**Comment by Naeemur** [comment]
Fixed in v1.1.0
