### ISSUE TITLE
Add ActivityIndicator while image is loading

### ISSUE THREAD

**Issue by tickietackie** [Naeemur/react-native-wheel-color-picker#6]
Would it be possible for you to add an ActivityIndicator while the image is loading. Maybe a configurable property for that?
I'm using this for a project with a very constrained bandwidth. The user therefore just sees an empty field at the beginning which is a bit annoying.

**Comment by Naeemur** [comment]
In v1.3.0
prop added: wheelLoadingIndicator
prop added: sliderLoadingIndicator
See README.md please.
