### ISSUE TITLE
Option to show only the color's wheel

### ISSUE THREAD

**Issue by gabrielsd02** [Naeemur/react-native-wheel-color-picker#7]
Hello, I'm from Brazil, in my project I would like to use only the wheel without slider. Could this option/feature be available soon ?

**Comment by hoebat** [comment]
I'd like to have this option as well.

**Comment by hoebat** [comment]
the code is here if you want to add a flag

https://github.com/Naeemur/react-native-wheel-color-picker/blob/master/ColorPicker.js#L593-L597

**Comment by Naeemur** [comment]
Version 1.2.0 released with PR merged and issues fixed. With this version you can use `swatches: false` & `sliderHidden:true` to achieve this.
